// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asdcbiucqqmvmfesrzra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZGNiaXVjcXFtdm1mZXNyenJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTkyODQsImV4cCI6MjA2ODA3NTI4NH0.jSeOp25yjvnsCIkoP9puNiB11K7aEMqx0lZ0gnOs-7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});